<?php
/**
 * Created by Jens F. https://m4taiori.de
 * GitHub: https://github.com/th3shadowbroker
 * Date: 03.07.2018
 * Time: 18:24
 */

const SPIGET4PHP_DEFAULT = null;

const SPIGET4PHP_CATEGORY_BUNGEE_BUKKIT = 2;
const SPIGET4PHP_CATEGORY_BUNGEE_PROXY = 3;
const SPIGET4PHP_CATEGORY_BUKKIT = 4;
const SPIGET4PHP_CATEGORY_TRANSPORTATION = 5;
const SPIGET4PHP_CATEGORY_CHAT = 6;
const SPIGET4PHP_CATEGORY_TOOLS_UTILITIES = 7;
const SPIGET4PHP_CATEGORY_MISC = 8;
const SPIGET4PHP_CATEGORY_LIBRARIES_APIS = 9;
const SPIGET4PHP_CATEGORY_TRANSPORTATION2 = 10;
const SPIGET4PHP_CATEGORY_CHAT2 = 11;